### PR TITLE
Add support for "shortConnectorIdNotification" event.

### PR DESCRIPTION
**Pull request by mpaperno**
Pretty much as the title says...  :)   Tested and used with TP 3.0.6.

Thanks,
-Max

### CODE REVIEW

**Comment by oddbear** [comment]
Nice. I will look into it tomorrow. :)

**Comment by oddbear** [comment]
I am testing this now.
Since ShortId is just a mapping. Maybe a dictionary to convert long/short id's is a better approach.

What do you think, is it better for the user to do this themselves, or the SDK to do the mapping internally?
(I think the Java SDK does this internally, but that SDK is quite different)

**Comment by mpaperno** [comment]
I thought of this. Maybe in some cases an internally-managed mapping could be a helpful feature.  In my use case though, I don't think an automated mapping would be very helpful... unless it could be configured somehow (and, turned off, for those who don't need the overhead).  Let me illustrate...

My vJoy plugin's connectors have multiple data arguments (4+) but in my case I only care about two of those arguments to determine if a slider is unique (in my case, that it represents the same joystick axis as some other slider).  So when I create and lookup the mappings, they're "custom," not based on the complete/full Connector ID which I got in the short notification message. 

Now if I could specify which data attributes I cared about for the mapping... that could be cool.  But I'm still not sure as it may be different based on, say, the type of connector, or other data in that connector instance.

The whole business is rather complicated (and frankly a bit bizarre) and I wouldn't be surprised if they changed things down the line.  For example, there's no way to tell when a connector has been "unmapped," that is, when the short ID is no longer valid.  Or how it's not clear when exactly the short ID changes.  Or that TP sends short ID data about sliders which are no longer on the page....   🙄 

In any case I would definitely leave the "raw" functionality exposed to the plugin author and not lock them into anything.  And I'd also make a case for an API like this to be lean-and-mean w/out any undue hand-holding (or, a way to disable it).  Frankly I'd like to disable all the value checking in the various sending commands because I know I already do that on my end (and throwing an exception, or just a `return`, is only informative in debug, not to diagnose some issue a user is having).

Sorry you asked yet?  🤣

**Comment by oddbear** [comment]
Valid points.

I would personally prefer to have shortId's tracked internally, I think. But I have tried to have as little as possible _magic_ in this SDK.

The problem with connectorId is that it has been quite buggy for me. But most of the issues seems to have been fixed in 3.0.6.
There are still some edgecases I don't think is fixed. Like the connectorId containing user input.

Another relevant edge case is the broadcast event. This event does not seem to do anything useful in most cases, but is often used to trigger a "refresh all state". Since TP can have some issues with keeping the state between page navigation.

There is always hard to find the best approach for all, ex. the Java SDK has magic everywhere, but this is something I would rather have as an separated _extended SDK_.

I am therefore quite unsure of what is best for the users of this SDK, and needs some feedback to find that middle ground.

But we do have the `_client.SendMessage` and `OnUnhandledEvent` that should help if there is something not covered in this SDK.
...

For value checking, this is something that could be added to a configuration, with the ability to turn on or off...
Ex. for value checking:
```csharp
if (value < 0 || value > 100)
    return false;

//Replace with:
_validator.ThrowIfNotInRange(value, 0, 100); //With configuration to skip if configured to be turned off.
```

**Comment by mpaperno** [comment]
> There are still some edgecases I don't think is fixed. Like the connectorId containing user input.

Yes exactly, you reminded me. In addition to a couple choices, "my" connectors have 3 freeform value fields where the user enters any numbers (or even variables/calculations).  It's completely pointless, in my case, to track all those instances separately (except for their short IDs). E.g. I just want all the ones which have, say, Axis X selected in one of the choices, and I will group those together. Then when Axis X changes, I can quickly run through the short IDs of just those connector(s) which are attached to that axis.

And yes, if the TP user is editing a lot of connector values, we end up with a lot of useless short IDs. As I said there's no way to remove them.  In fact that reminds me to make a safeguard against the lookup table filling up!

> Another relevant edge case is the broadcast event.

Only possible use I could ever think for this is if the plugin user is instructed to name their page(s) with a certain pattern, then the plugin could know the use switched to a relevant page.  Edge case, indeed.

> but is often used to trigger a "refresh all state".

Yeah don't get me started on _that_....

> There is always hard to find the best approach for all, ex. the Java SDK has magic everywhere, but this is something I would rather have as an separated extended SDK.

I hear you very well on that.  It's always a balance.  Personally I think programmers should know what they're doing and all this handholding isn't helping anyone in the long run....  :-P  There's a chance I'm slightly jaded after 40 years though.  But if you look at "old school" APIs where speed and efficiency are key, they aren't holding any hands.  It's up to the API user to decide how much or how little time/energy/computing should be spent on error trapping/logging/etc.

It is, however, always nice to have extra tools available when you need them, whether it's some option built into the API, an extension, external, whatever.

> For value checking, this is something that could be added to a configuration, with the ability to turn on or off...

Something like that would fit both positions (hand-holding and "raw") perfectly.  👍🏼 

Now to check this fail.... 

Cheers,
-Max

**Comment by mpaperno** [comment]
Ah. What is annoying is the lack of default base method implementations in Interfaces. I understand it's available in a newer C# version or something.  Not sure I grok yet why an `Interface` is better than the old abstract base class with "Interface" in the name... 🤣 

I'll stick something in the sample....

**Comment by oddbear** [comment]
Always appreciate feedback. I only have had one usecase yet for connectors except for the "sample" plugin, and that one is quite limited. So this helps a lot. :)

At the Touch Portal plugin dev channel, I get one hit for `shortId` when searching, so this is not something that is used in to many plugins yet.

**Comment by mpaperno** [comment]
I can never find anything on Discord.  Great for chatting, useless as a reference.  BTW I'm max.paperno over there.  And yea it cost me some brain cells trying to get the connector updates working (more or less).  And the "up" (connector release) detection sucks.  I was tempted several times to ask in Discord if anyone has actually used them...  :)

Anyway, I think it helps make the case to wait on doing anything too deep with the current setup.  Another thing to consider in any API is that it's relatively easy to add stuff, but if people actually use that feature, it's much harder to change or remove it later.

**Comment by mpaperno** [comment]
Done, with bonus docs! :)  I punted on short IDs with "See the TP API documentation for usage details."  :-D

**Comment by oddbear** [comment]
For these kind of discussions, usually it happens on this channel, seems like you should be there to (if your not here already):
image

But I do think only one of the mods are allowed to invite.
image

**Comment by mpaperno** [comment]
Yep, been there.  I have [another plugin](https://github.com/mpaperno/LGKeys-TouchPortal-Plugin) published, brushing up on Python, which led me to rewrite most of [that API](https://github.com/KillerBOSS2019/TouchPortal-API). Lately have been working on the [MSFS plugin](https://github.com/tlewis17/MSFSTouchPortalPlugin) (learned my C#), which led me to your API (thanks!), and then I realized I couldn't emulate a joystick with TP (thought it had that feature but I guess it was that "other" app).  vJoy has a C++ API with C# wrapper, and with the former I would need to write a TP client also (I think).  Anyway I already had VS open so here we are  :-)

Thanks for the merge!

**Comment by mpaperno** [comment]
> > For value checking, this is something that could be added to a configuration, with the ability to turn on or off...
> 
> Something like that would fit both positions (hand-holding and "raw") perfectly. 👍🏼

BTW I realized there is double validation going on in Client.  Once before creating the Command to send, and then again inside the command constructor.  Right?  It would be more efficient to just try/catch the construction (or remove validation from the command c'tors).

-Max

**Pull request merged**
